#!/usr/bin/env node

const fs = require('fs');
const os = require('os');
const path = require('path');

const download = require('download');

const [, , version, destination] = process.argv;

const baseUrl = `https://github.com/gohugoio/hugo/releases/download/v${version}/`;

const urlMap = {
  darwin: `${baseUrl}hugo_extended_${version}_macOS-64bit.tar.gz`,
  linux: `${baseUrl}hugo_extended_${version}_Linux-64bit.tar.gz`,
  win32: `${baseUrl}hugo_extended_${version}_Windows-64bit.zip`
};

const dest = path.resolve(destination);

fs.mkdirSync(dest, { recursive: true });

const url = urlMap[os.platform()];

download(url, dest, { extract: true })
  .then(function () {
    fs.unlinkSync(path.resolve(dest, 'LICENSE'));
    fs.unlinkSync(path.resolve(dest, 'README.md'));
  })
  .catch(function (err) {
    console.error(err);
    process.exitCode = 1;
  });
